# Base configs
baseurl: "http://nitinlalwani.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-109695683-1"

# UI configs
title: "Nitin Lalwani Photography"
subtitle: "See the world through my camera!"
author: "Nitin Lalwani"
bio: "I am a developer cum photographer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
web_design: "Vatsal Mistry"
social_urls:
  facebook: "https://www.facebook.com/nitin.lalwani.334"
  twitter: "#"
  instagram: "https://www.instagram.com/nitinlalwani02"
  linkedin: "#"
  github: "https://github.com/nitinlalwani"
